### PR TITLE
Replace several preview.net.imglib2 classes by their equivalents from net.imglib2

### PR DESCRIPTION
**Pull request by tpietzsch**
Replace several preview.net.imglib2 classes by their equivalents from net.imglib2.
And update POM parent to pom-scijava 31.1.0

### CODE REVIEW

**Comment by maarzt** [comment]
Thanks @tpietzsch for suggesting this clean up.

I could only find one difference between the duplicated code that is removed in this PR, and the original code in imglib2-algorithm. The Gauss3 that is used by Labkit uses the imglib2 Parallelization class. The Gauss3 in imglib2-algorithm uses Java's fixed thread pool executer service. Surprisingly this small difference has a big impact. The code using the Parallelization class is 35% faster. My measurements are very sketchy for now, and not unbiased as I previously fine tuned the performance using the Parallelization class. But it indicates that the Parallelization class is indeed a good way to optimize image processing code for multi threading.

We should probably use the Parallelization class more in imglib2-algorithm. And I should write a tutorial for it.

**Comment by maarzt** [comment]
This PR can be merged after https://github.com/imglib/imglib2-algorithm/pull/93 is merged and released. The performance of Labkits CPU classifier will otherwise drop by 30 %.

**Comment by tpietzsch** [comment]
> This PR can be merged after [imglib/imglib2-algorithm#93](https://github.com/imglib/imglib2-algorithm/pull/93) is merged and released. The performance of Labkits CPU classifier will otherwise drop by 30 %.

Merged and released in `imglib2-algorithm-0.12.1`.
I updated this PR to use the new version.

**Comment by tpietzsch** [comment]
I updated the PR again to be up-to-date with the recent package renaming.
This can be merged now, right?

**Comment by maarzt** [comment]
@tpietzsch Could you update imglib2-algorithm on the Fiji update site?

**Comment by tpietzsch** [comment]
@tpietzsch Could you update imglib2-algorithm on the Fiji update site?

I just uploaded it.

**Pull request merged**
