### PR TITLE
Fix POM to support melting pot testing

### PR DESCRIPTION
**Pull request by ctrueden**
- Happy New Year 2023
- POM: split out version properties and update info

### CODE REVIEW

**Comment by ctrueden** [comment]
@maarzt Right now, the pom-scijava melting-pot needs to recompile labkit-pixel-classification every time, even when no dependencies have changed, because of hardcoded `<version>`s. Can we get this merged and released, so that the melting-pot can be more efficient? Thanks!

**Comment by ctrueden** [comment]
It looked like some transient network failure to me. You must have re-run it? Because the check is green now...

**Comment by maarzt** [comment]
Sorry, my fault. I missed that you already fixed the problem.

**Comment by ctrueden** [comment]
Thanks @maarzt! I updated pom-scijava accordingly (scijava/pom-scijava@78025f30e4c2e3497773b4373ead2db919a22118).

**Pull request merged**
